### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by danny-su** [valantic/mutation-tester#7]
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Optional.of(Optional.java:113)
	at com.valantic.intellij.plugin.mutation.services.impl.ModuleService.updateModule(ModuleService.java:82)
	at com.valantic.intellij.plugin.mutation.services.impl.ModuleService.getOrCreateRunConfigurationModule(ModuleService.java:68)
	at com.valantic.intellij.plugin.mutation.commandline.MutationCommandLineState.lambda$new$0(MutationCommandLineState.java:83)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.valantic.intellij.plugin.mutation.commandline.MutationCommandLineState.<init>(MutationCommandLineState.java:80)
	at com.valantic.intellij.plugin.mutation.configuration.MutationConfiguration.getState(MutationConfiguration.java:86)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:213)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:96)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:741)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:694)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$default(ExecutionManagerImpl.kt:651)
	at com.intellij.execution.impl.ExecutionManagerImpl$restartRunProfile$1.run(ExecutionManagerImpl.kt:549)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:388)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by fhuesig** [comment]
In this case it seems like your targetTests were not provided. I created a small update. In a case its gonna try to get the fallback module. It might take 24 hours until it is in IntelliJ Marketplace. You can also download it here https://github.com/valantic/mutation-tester/releases/tag/v1.1.1

i apologize for the delayed answer. I just updated email notifications for this plugin.

Keep me uptodate with your issue. Otherwise I will close this soon. Thank you for your feedback!

**Comment by fhuesig** [comment]
after 10 days after updating version there was no followup. Closing this issue now.
